import { Inter } from "next/font/google";
import "./globals.css";
import Main from "./main";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100..700;1,100..700&family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap" rel="stylesheet" />
      </head>
      <body
        suppressHydrationWarning
        className={inter.className}
        style={{ height: "100%", width: "100%" }}
      >
        <Main>{children}</Main>
      </body>
    </html>
  );
}
