export const dynamic = "force-dynamic";
import { Inter } from "next/font/google";
import '@fontsource/space-grotesk';
import '@fontsource/inter';
import "./globals.css";
import Main from "./main";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "VidyaAI",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const locale = await getLocale();

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body
        suppressHydrationWarning
        className={inter.className}
        style={{ height: "100%", width: "100%", fontFamily: "Inter, sans-serif" }}
      >
        <NextIntlClientProvider messages={messages}>
          <Main>{children}</Main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}