import { Inter } from "next/font/google";
import '@fontsource/space-grotesk';
import "./globals.css";
import Main from "./main";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "VidyaAI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={inter.className}
        style={{ height: "100%", width: "100%" }}
      >
        <Main>{children}</Main>
      </body>
    </html>
  );
}
