import React from 'react';

const PrivacyPolicy = () => {
  return (
    <div style={{ padding: '20px', fontFamily: 'Arial, sans-serif', maxWidth: '800px', margin: '0 auto' }}>
      <h1 style={{margin:"14px auto"}}>Privacy Policy for Vidya AI</h1>
      <p style={{margin:"4px auto"}}><strong>Last updated:</strong> 12th March 2025</p>

      <p>
        This Privacy Policy describes the policies and procedures of IndiqAI (&quot;Company,&quot; &quot;We,&quot; &quot;Us,&quot; or &quot;Our&quot;) on the collection, use, and disclosure of your information when you use Vidya AI (&quot;Service&quot;), a web-based AI-powered ed-tech platform. It also explains your privacy rights and how the law protects you.
      </p>

      <p>
        By using Vidya AI, you agree to the collection and use of your information in accordance with this Privacy Policy.
      </p>

      <h2 style={{margin:"14px auto"}}>Interpretation and Definitions</h2>
      <h3>Interpretation</h3>
      <p>
        Words with capitalized initial letters have meanings defined under the following conditions. These definitions apply whether the terms appear in singular or plural.
      </p>

      <h3 style={{margin:"7px auto"}}>Definitions</h3>
      <p>
        For the purposes of this Privacy Policy:
      </p>
      <ul style={{ display: "flex", flexDirection: "column", gap: "6px", }}>
        <li><strong>Account</strong> means a unique account created for you to access Vidya AI or parts of the Service.</li>
        <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of shares, equity interest, or other securities entitled to vote for the election of directors or other managing authority.</li>
        <li><strong>Application</strong> refers to Vidya AI, the web-based software program provided by IndiqAI.</li>
        <li><strong>Company</strong> (referred to as &quot;the Company,&quot; &quot;We,&quot; &quot;Us,&quot; or &quot;Our&quot;) refers to IndiqAI, Delhi, India.</li>
        <li><strong>Country</strong> refers to India.</li>
        <li><strong>Device</strong> means any device that can access the Service, such as a computer, smartphone, or digital tablet.</li>
        <li><strong>Personal Data</strong> means any information relating to an identified or identifiable individual.</li>
        <li><strong>Service</strong> refers to the Vidya AI web application.</li>
        <li><strong>Service Provider</strong> means any natural or legal person who processes data on behalf of the Company. This includes third-party companies or individuals employed to facilitate, provide, or analyze the Service.</li>
        <li><strong>Usage Data</strong> refers to data collected automatically, either generated by your use of the Service or from the Service infrastructure itself (e.g., page visit duration).</li>
        <li><strong>You</strong> means the individual accessing or using the Service, or the company or legal entity on behalf of which such an individual is accessing or using the Service.</li>
      </ul>

      <h2 style={{margin:"14px auto"}}>Collecting and Using Your Personal Data</h2>
      <h3 style={{margin:"7px auto"}}>Types of Data Collected</h3>
      <h4 style={{margin:"4px auto"}}>Personal Data</h4>
      <p>
        While using Vidya AI, we may ask you to provide personally identifiable information that can be used to contact or identify you. This may include, but is not limited to:
      </p>
      <ul>
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Usage Data</li>
      </ul>

      <h4 style={{margin:"4px auto"}}>Usage Data</h4>
      <p>
        Usage Data is collected automatically when you use the Service. This may include:
      </p>
      <ul>
        <li>Your Device Internet Protocol (IP) address</li>
        <li>Browser type and version</li>
        <li>Pages visited on Vidya AI</li>
        <li>Time and date of your visit</li>
        <li>Time spent on pages</li>
        <li>Unique device identifiers and diagnostic data</li>
      </ul>

      <p style={{margin:"4px auto"}}>
        If you access Vidya AI via a mobile device, we may also collect:
      </p>
      <ul>
        <li>Mobile device type</li>
        <li>Mobile device unique ID</li>
        <li>Mobile device IP address</li>
        <li>Mobile operating system</li>
        <li>Mobile browser type</li>
        <li>Other diagnostic data</li>
      </ul>

      <h4 style={{margin:"4px auto"}}>Information Collected While Using the Application</h4>
      <p>
        With your prior permission, we may collect:
      </p>
      <ul>
        <li>Pictures and other information from your Device&apos;s camera and photo library</li>
      </ul>
      <p>
        This information is used to provide and improve the Service. You can enable or disable access to this information at any time through your Device settings.
      </p>

      <h2 style={{margin:"14px auto"}}>Use of Your Personal Data</h2>
      <p>
        The Company may use Personal Data for the following purposes:
      </p>
      <ul>
        <li>To provide, maintain, and monitor the usage of the Service.</li>
        <li>To manage your Account and provide access to Service functionalities.</li>
        <li>To perform contractual obligations, including the development and compliance of purchase contracts.</li>
        <li>To contact you via email, phone, SMS, or other electronic communication methods regarding updates, security, or informative communications.</li>
        <li>To provide news, special offers, and general information about goods, services, or events similar to those you have purchased or inquired about (unless you opt out).</li>
        <li>To manage your requests and inquiries.</li>
        <li>For business transfers, such as mergers, acquisitions, or asset sales.</li>
        <li>For data analysis, identifying usage trends, evaluating promotional campaigns, and improving the Service.</li>
      </ul>

      <h2 style={{margin:"14px auto"}}>Sharing Your Personal Data</h2>
      <p>
        We may share your personal information in the following situations:
      </p>
      <ul>
        <li>With <strong>Service Providers</strong> to monitor and analyze Service usage or to contact you.</li>
        <li>For <strong>business transfers</strong>, such as mergers, acquisitions, or asset sales.</li>
        <li>With <strong>Affiliates</strong>, provided they honor this Privacy Policy.</li>
        <li>With <strong>business partners</strong> to offer you products, services, or promotions.</li>
        <li>With <strong>other users</strong> when you interact in public areas of the Service.</li>
        <li>With your <strong>consent</strong> for any other purpose.</li>
      </ul>

      <h2 style={{margin:"14px auto"}}>Retention of Your Personal Data</h2>
      <p>
        We retain your Personal Data only as long as necessary for the purposes outlined in this Privacy Policy. This includes complying with legal obligations, resolving disputes, and enforcing agreements. Usage Data is retained for shorter periods unless required to improve Service security or functionality.
      </p>

      <h2 style={{margin:"14px auto"}}>Transfer of Your Personal Data</h2>
      <p>
        Your information, including Personal Data, may be processed and stored outside your jurisdiction, where data protection laws may differ. By using Vidya AI, you consent to such transfers. We ensure your data is treated securely and in accordance with this Privacy Policy.
      </p>

      <h2 style={{margin:"14px auto"}}>Deleting Your Personal Data</h2>
      <p>
        You have the right to delete or request assistance in deleting your Personal Data. You can update, amend, or delete your information through your Account settings or by contacting us. Note that we may retain certain information to comply with legal obligations.
      </p>

      <h2 style={{margin:"14px auto"}}>Disclosure of Your Personal Data</h2>
      <p>
        We may disclose your Personal Data:
      </p>
      <ul>
        <li>During <strong>business transactions</strong>, such as mergers or acquisitions.</li>
        <li>To comply with <strong>legal obligations</strong> or respond to valid requests by public authorities.</li>
        <li>To protect the rights, property, or safety of the Company, users, or the public.</li>
      </ul>

      <h2 style={{margin:"14px auto"}}>Security of Your Personal Data</h2>
      <p>
        While we strive to protect your Personal Data using commercially acceptable means, no method of transmission or storage is 100% secure. We cannot guarantee absolute security.
      </p>

      <h2 style={{margin:"14px auto"}}>Children&apos;s Privacy</h2>
      <p>
        Vidya AI does not address anyone under the age of 13. We do not knowingly collect Personal Data from children under 13. If you are a parent or guardian and believe your child has provided us with Personal Data, please contact us.
      </p>

      <h2 style={{margin:"14px auto"}}>Links to Other Websites</h2>
      <p>
        Vidya AI may contain links to third-party websites. We advise you to review their Privacy Policies, as we have no control over their content or practices.
      </p>

      <h2 style={{margin:"14px auto"}}>Changes to This Privacy Policy</h2>
      <p>
        We may update this Privacy Policy periodically. We will notify you of changes by posting the updated policy on this page and updating the &quot;Last updated&quot; date. You are advised to review this policy regularly.
      </p>

      <h2 style={{margin:"14px auto"}}>Contact Us</h2>
      <p>
        If you have questions about this Privacy Policy, contact us:
      </p>
      <ul>
        <li>By email: <a href="mailto:support@indiqai.com">support@indiqai.com</a></li>
        <li>By visiting: <a href="https://www.indiqai.ai/">https://www.indiqai.ai/</a></li>
      </ul>
    </div>
  );
};

export default PrivacyPolicy;